//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esubao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fahuo
    {
        public string Express_number { get; set; }
        public string OOnsignor { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
        public string Address { get; set; }
        public string Shipping_outlets { get; set; }
        public string Dot_information { get; set; }
        public string Corporate_name { get; set; }
        public Nullable<int> Delivery_Express { get; set; }
    
        public virtual transportation transportation { get; set; }
    }
}
