//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esubao.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EsuBaoEntities : DbContext
    {
        public EsuBaoEntities()
            : base("name=EsuBaoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Fahuo> Fahuos { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<Shouhuo> Shouhuos { get; set; }
        public virtual DbSet<T_AdminUser> T_AdminUser { get; set; }
        public virtual DbSet<T_expreMiss> T_expreMiss { get; set; }
        public virtual DbSet<T_Refund> T_Refund { get; set; }
        public virtual DbSet<transportation> transportations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ZiXunJianYi> ZiXunJianYis { get; set; }
        public virtual DbSet<Tousu> Tousus { get; set; }
        public virtual DbSet<T_replay> T_replay { get; set; }
    }
}
