//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esubao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_replay
    {
        public int Replay_id { get; set; }
        public string Replay_mess { get; set; }
        public int advice_id { get; set; }
        public System.DateTime Replay_date { get; set; }
        public string Replay_zt { get; set; }
    
        public virtual ZiXunJianYi ZiXunJianYi { get; set; }
    }
}
