//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esubao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tousu
    {
        public int Tousu_id { get; set; }
        public string Tousu_title { get; set; }
        public string Tousu_name { get; set; }
        public string role { get; set; }
        public string Contact_number { get; set; }
        public string Waybill_No { get; set; }
        public string Tousu_Message { get; set; }
        public System.DateTime Tousu_Date { get; set; }
    }
}
