//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esubao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_Id { get; set; }
        public string User_uaername { get; set; }
        public string User_password { get; set; }
        public string User_Name { get; set; }
        public string User_Sex { get; set; }
        public string User_Company { get; set; }
        public string User_fixedphone { get; set; }
        public string User_Phone { get; set; }
        public string User_Email { get; set; }
        public string User_city { get; set; }
        public string User_note { get; set; }
    }
}
