//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esubao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZiXunJianYi
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string Message_type { get; set; }
        public string Message_person { get; set; }
        public string Contact_number { get; set; }
        public string Mail_box { get; set; }
        public string Waybill_No { get; set; }
        public string Message { get; set; }
        public System.DateTime MessDate { get; set; }
    }
}
